FROM docker.io/ubuntu:20.04

RUN apt-get update \
    && \
    DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true \
    apt-get install --yes --quiet=2 \
    build-essential \
    wget \
    git \
    gawk \
    flex \
    bison \
    openssl \
    libssl-dev \
    dkms \
    libelf-dev \
    libudev-dev \
    libpci-dev \
    libiberty-dev \
    autoconf \
    bc \
    rsync \
    cpio \
    lz4 \
    kmod \
    libncurses5-dev \
    dwarves\
    && apt-get clean
